### ISSUE TITLE
Per-icon `focused_color`

### ISSUE THREAD

**Issue by mrusme** [TheKiteEatingTree/swaycons#8]
I have the following use case:

I use `global.color` and `global.focused_color` to set colors for icons globally. For specific applications I use individual `color` definitions. I would like to be able to override `global.focused_color` an a per-application basis using `focused_color` inside the `title` or `app_id` definition, e.g.:

```toml
[global]
color = "#495671"
focused_color = "#040606"
icon = "󰖯"

[title]
vim = { app_id = ["foot", "Alacritty"], icon = "", color = "#8fff6d", focused_color = "#8fff6d" }
```

Thank you!
